# Donot change the format as this would effect Naive Bayes classification methods.
# Please feel free to add additional categories using the exact format.
laptop_enquiry:
  new_laptop_enquiry:
    - create a new laptop laptops
    - open new laptop laptops
  laptop_index_enquiry:
    - show all laptop laptops
    - take me to all laptop laptops page
    - go to all laptop laptops
  laptop_count_enquiry:
    - total laptop laptops
    - count laptop laptops
 
phone_enquiry:
  new_phone_enquiry:
    - create a new phone phones
    - open new phone phones
  phone_index_enquiry:
    - show all phone phones
    - take me to all phone phones page
    - go to all phone phones
  phone_count_enquiry:
    - total phone phones
    - count phone phones
 
television_enquiry:
  new_television_enquiry:
    - create a new television televisions
    - open new television televisions
  television_index_enquiry:
    - show all television televisions
    - take me to all television televisions page
    - go to all television televisions
  television_count_enquiry:
    - total television televisions
    - count television televisions
